package:
  name: oitg
  version: {{ environ.get("GIT_DESCRIBE_TAG", "") }}

source:
  git_url: ../..

build:
  noarch: python
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  string: py38_{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}+git{{ environ.get("GIT_DESCRIBE_HASH", "")[1:] }}
  script: python setup.py install

requirements:
  build:
    - python >=3.8
    - setuptools
    - statsmodels
  run:
    - python >=3.8
    - numpy
    - h5py
    - statsmodels
    - scipy
