version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  test:
    executor:
      name: python/default
      tag: "3.10"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
         name: Run unit tests
         command: poetry run poe test
      - run:
          name: Verify that Flake8 passes
          command: poetry run poe lint
      - run:
          name: Check that YAPF doesn't change formatting
          command: poetry run poe fmt-test
  docs-build:
    executor:
      name: python/default
      tag: "3.10"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Build documentation
          command: cd docs && poetry run make html
      - persist_to_workspace:
          root: docs/_build
          paths: html
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: docs/_build
      - run:
          name: Disable jekyll builds
          command: touch docs/_build/html/.nojekyll
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config --global user.email "david.nadlinger@physics.ox.ac.uk"
            git config --global user.name "CircleCI builder"
      - add_ssh_keys:
          fingerprints:
            - "22:ab:6c:2d:f5:59:9b:8c:1a:3f:e9:9f:74:5b:e4:e2"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Update docs" --dist docs/_build/html
workflows:
  build:
    jobs:
      - test
      - docs-build
      - docs-deploy:
          requires:
            - test
            - docs-build
          filters:
            branches:
              only: master
